# Generated by Django 5.2.1 on 2025-05-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('visualinventory', '0003_make_categories_without_locations_possible'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dx',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='location',
            name='dy',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='location',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('dx__gt', 0)), name='positive_dx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('dy__gt', 0)), name='positive_dy'),
        ),
    ]
