# Generated by Django 5.0.3 on 2024-03-22 19:00

from django.db import migrations


def create_initial_space(apps, schema_editor) -> None:
    Location = apps.get_model("locations", "Location")
    initial_space = Location(pk=1, name="Initial space", parent=None)
    initial_space.save()


class Migration(migrations.Migration):
    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_space)
    ]
