# Generated by Django 5.0.3 on 2024-03-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_create_initial_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='locations',
            field=models.ManyToManyField(related_name='categories', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locations.category'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.location'),
        ),
    ]
