# Generated by Django 5.0.3 on 2024-03-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_category_locations_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='locations',
            field=models.ManyToManyField(related_name='stored_categories', to='locations.location'),
        ),
    ]
